---
title: "mapping_EEC-ECC_genes"
author: "Javier Escudero"
date: "2023-08-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Loading libraries
```{r}
rm(list=ls())

library(semla)
library(viridis)
library(ggplot2)
library(patchwork)
library(tidyverse)
```

Setting directories
```{r}
st.dir <- "your path to where the manually curated HV data is located"
vis.dir <- "your path to where to export the plots"
```

# Summary
In this markdown we want to check the distribution of marker genes for celltypes EEC and ECC.

# Analysis
## Loading ST data
Load the detailed QCed object
```{r}
se <- readRDS(list.files(st.dir, pattern = "HV.rds", full.names = TRUE))
se <- LoadImages(se, image_height = 2000)
```

```{r}
super.annotation <- select(se[[]],c(Group, Tissue.region, PIN)) %>%
  unite("super_anno", Group:PIN, sep = " : ", remove = TRUE)
se <- AddMetaData(se, super.annotation)
```

## Marker genes
```{r}
genes.interest <- list(general = c("CHGA", "CHGB","PCSK1N"),
                       ECC_progen = c("SOX4","HES6","PROX1"),
                       L_EEC = c("GCG","PYY"),
                       D_EEC = c("SST"),
                       ECC = c("TPH1"))
```

## Plotting
Plotting all sections at the same time
```{r}
plot_genes <- function(se_obj, gene_list, p){
  iwalk(gene_list, function(genes, id){
    walk(genes, function(gene){
      #generate the plot for each gene for all the sections
      p1 <- MapFeatures(se_obj, features = gene, image_use = "raw", ncol = 3,
                        colors = heat.colors(11), 
                        scale = "shared", 
                        label_by = "super_anno",
                        scale_alpha = TRUE,
                        pt_size = 2, override_plot_dims = TRUE) +
        plot_layout(guides = "collect") &
        labs(fill = "Gene expression",
             subtitle = "") &
        plot_annotation(subtitle = paste0(gene, " - ", id," marker"),
                        theme = theme(plot.subtitle = element_text(size = 30, 
                                                                   face = "bold",
                                                                   hjust = 0.5))) &
        theme(legend.position = "right", 
              legend.text = element_text(angle = 0, size = 20),
              legend.title = element_text(size = 20),
              legend.key.size = unit(2, "cm"),
              plot.title = element_text(size = 25)) 
      
      ggsave(paste0(vis.dir, "/spatial_plots/groupped/",p,"/",id,"_markers/", gene,"_HE.png"),
             plot=p1,
             width=25, height=12)  
      # no HE
      p2 <- MapFeatures(se_obj, features = gene, 
                        ncol = 3,
                        colors = rev(magma(11)),
                        scale = "shared", 
                        label_by = "super_anno",
                        scale_alpha = FALSE,
                        pt_size = 1.75, override_plot_dims = TRUE) +
        plot_layout(guides = "collect") &
        labs(fill = "Gene expression",
             subtitle = "") &
        plot_annotation(subtitle = paste0(gene, " - ", id, " marker"),
                        theme = theme(plot.subtitle = element_text(size = 30, 
                                                                   face = "bold",
                                                                   hjust = 0.5))) &
        theme(legend.position = "right", 
              legend.text = element_text(angle = 0, size = 20),
              legend.title = element_text(size = 20),
              legend.key.size = unit(2, "cm"),
              plot.title = element_text(size = 25)) 
      ggsave(paste0(vis.dir, "/spatial_plots/groupped/",p,"/",id,"_markers/", gene,"_noHE.png"),
             plot=p2,
             width=25, height=12)
    })
  })
}
```

```{r}
plot_genes(se_obj = SubsetSTData(se, expression = Tissue == "colon"),
           gene_list = genes.interest,
           p = "colon")
plot_genes(se_obj = SubsetSTData(se, expression = Tissue == "rectum"),
           gene_list = genes.interest,
           p = "rectum")
```

# Meta
```{r}
date()
sessionInfo()
```

