---
title: "exporting_updated_sc_counts"
author: "Javier Escudero"
date: "2023-03-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Setting up directories
```{r}
rm(list=ls())

library(STutility)
library(tidyverse)
```

Setting up directories
```{r}
sc.dir <- "your path to the single cell rds object"
out.dir <- "your path to where you want to export the data"
```

# Analysis
## Loading data
```{r}
sc.hv <- readRDS(list.files(sc.dir, full.names = TRUE, pattern = "Fig1")) 
sc.hv <- NormalizeData(sc.hv, normalization.method = "LogNormalize")
```

Computing variable genes
```{r}
variable.hv <- sc.hv %>%
  FindVariableFeatures(selection.method = "vst", nfeatures = 4000) %>% 
  VariableFeatures()
```


## Subsetting data
```{r}
hv.mta.data <- data.frame(celltype = gsub(".*#","",as.character(sc.hv$new_anno_celltype_cluster)),
                             patient_id = sc.hv$PIN) %>%
  rownames_to_column(var = "cell_id") 
```

Exploring a bit
```{r}
celltype_colors <- setNames(Polychrome::light.colors(n=20),
                            sort(unique(hv.mta.data$celltype)))

plot_df <- select(hv.mta.data, c(patient_id, celltype)) %>%
  group_by(patient_id, celltype) %>%
  summarise(count = n()) %>%
  group_by(patient_id) %>%
  mutate(prop_cells = count/sum(count))
plot <- ggplot(plot_df, aes(x = patient_id, y = prop_cells, fill = celltype)) +
    geom_bar(stat = "identity") +
    scale_fill_manual(values = celltype_colors) +
    facet_grid(~ .data[["patient_id"]], scales ="free") +
    theme(axis.text.x = element_text(angle = 90),
          plot.title = element_text(face = "bold"),
          strip.text.x = element_text(face = "bold"),
          legend.title = element_text(face = "bold"))

plot
```

Actual subsetting
```{r}
subset_group_subgroup <- function(mta_data, group, subgroup){
  set.seed(9)
  
  sub_mta_data <- map_dfr(unique(mta_data[[group]]), function(this_type){
    #keeping only cells for the celltype of interest
    anno_this_type <- mta_data %>%
      filter(.data[[group]] == this_type)
    #getting cells from each patient
    samp_anno <- map(unique(anno_this_type[[subgroup]]), function(patientID){
      pat_anno <- filter(anno_this_type, .data[[subgroup]] == patientID)
      #how many cells in celltype for this patient
      cells_this <- nrow(pat_anno)
      #setting up number for downsampling
      if (cells_this >= 100) {
        message("Keeping 100 cells for ", this_type, " in ",patientID)
        n_cells = 100
      } else if (cells_this < 25) {
        message("Dropping ", this_type, ", not enough cells in ", patientID)
        return(NULL)
      } else {
        n_cells = cells_this
        message("Keeping ", n_cells," cells for ",this_type," in ",patientID)
      }
      #downsampling
      pat_anno <- slice_sample(pat_anno, n=n_cells)
      
      return(pat_anno)
    })
    return(samp_anno)
  })
  return(sub_mta_data)
}
```

```{r}
cells.hv <- subset_group_subgroup(hv.mta.data, "celltype","patient_id") 
```

After subsetting the metadata, we must subset the count data
```{r}
get_cnt_data <- function(se_obj, genes_keep, cells_keep){
  count_data <- t(as.matrix(GetAssayData(se_obj, slot = "counts")[genes_keep, cells_keep])) %>%
    as_tibble(rownames = NA) 
  clean_count_data <- count_data[,colSums(count_data[]) > 0] %>%
    mutate(cell_id = rownames(count_data), .before = 1)
}
```

```{r}
cnt.HV <- get_cnt_data(sc.hv, variable.hv, cells.hv$cell_id)
variable.hv <- intersect(variable.hv, colnames(cnt.HV))
```

Exporting data
```{r}
#healthy
write_tsv(cnt.HV, file = paste0(out.dir, "/HV_cnt_matrix.tsv"))
write_tsv(select(cells.hv, c(cell_id, celltype)), 
                 file = paste0(out.dir, "/HV_mta_data.tsv"))
```

# Details
```{r}
date()
sessionInfo()
```




